[package]
name = "studyline-daemon"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
studyline-graph-core = { path = "../studyline-graph-core" }
tokio = { workspace = true }
axum = { workspace = true }
tower-http = { workspace = true }
notify-debouncer-mini = { workspace = true }
notify = { workspace = true }
futures-util = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
walkdir = { workspace = true }
